// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBP-HVp53NlZqEqdcTVGIwGMQd8bZf5d1Q",
  authDomain: "myapplication-10-58a1a.firebaseapp.com",
  projectId: "myapplication-10-58a1a",
  storageBucket: "myapplication-10-58a1a.firebasestorage.app",
  messagingSenderId: "473018387336",
  appId: "1:473018387336:web:af679eb119410353cb883d",
  measurementId: "G-LKTNW4N5E7"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowt4zaP8xl4CskqdJ2i0ACfnGVMgsPw0',
    appId: '1:837361121774:android:a762040372ebc1b97d36ff',
    messagingSenderId: '837361121774',
    projectId: 'mobile-app-91fb7',
    storageBucket: 'mobile-app-91fb7.firebasestorage.app',
  );
}